version: '3'

services:
  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG}
    restart: ${DOCKER_RESTART}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '${POSTGRES_PORT}:5432'

  app:
    image: ${APP_IMAGE_NAME}:${APP_IMAGE_TAG}
    restart: ${DOCKER_RESTART}
    volumes:
      - app_log:/src/log
      - app_media:/src/media
      - app_static:/src/assets
    env_file:
      - ${APP_ENV_FILE}
    sysctls:
      net.core.somaxconn: 4096
    depends_on:
      - postgres

  caddy:
    image: caddy:2-alpine
    restart: ${DOCKER_RESTART}
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      - app_media:/srv/media:ro
      - app_static:/srv/assets:ro
    environment:
      SITE_ADDRESS: ${CADDY_SITE_ADDRESS}
    ports:
      - '${CADDY_HTTP_PORT}:80'
      - '${CADDY_HTTPS_PORT}:443'
    depends_on:
      - app

volumes:
  app_log:
  app_media:
  app_static:
  caddy_data:
  caddy_config:
  postgres_data:
